# Generated by Django 4.2 on 2023-09-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudfront_id', models.CharField(max_length=32, null=True)),
                ('bucket_id', models.CharField(max_length=128, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
            options={
                'verbose_name': 'AWS',
                'verbose_name_plural': 'AWS',
            },
        ),
    ]
