# Generated by Django 4.2 on 2023-05-16 16:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aws',
            options={'verbose_name': 'AWS', 'verbose_name_plural': 'AWS'},
        ),
        migrations.AddField(
            model_name='aws',
            name='bucket_id',
            field=models.CharField(max_length=128, null=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AddField(
            model_name='aws',
            name='cloudfront_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
