# Generated by Django 4.2 on 2023-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_alter_aws_options_aws_bucket_id_aws_cloudfront_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='bucket_id',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
