- model: publish.Theme
  pk: 1
  fields:
    url: https://github.com/tcarwash/blue-penguin-dark.git
    user_settings: |
      DARK_LIGHT_SWITCHING_OFF=true
      DISPLAY_HEADER = true
      DISPLAY_FOOTER = true
      DISPLAY_HOME   = true
      DISPLAY_MENU   = true

- model: publish.Theme
  pk: 2
  fields:
    url: https://github.com/alexandrevicenzi/Flex/archive/refs/heads/v3.zip
    theme_settings: |
      LINKS = conf.MENUITEMS
