- model: publish.Theme
  pk: 1
  fields:
    url: https://github.com/tcarwash/blue-penguin-dark.git
    user_settings: |
      DARK_LIGHT_SWITCHING_OFF=true
      DISPLAY_HEADER = true
      DISPLAY_FOOTER = true
      DISPLAY_HOME   = true
      DISPLAY_MENU   = true
