# Generated by Django 4.2 on 2023-09-08 15:48

from django.db import migrations, models
import django.db.models.deletion
import velican2.engines.pelican.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32)),
                ('url', models.CharField(blank=True, help_text='Null for built-in plugins', max_length=265, null=True)),
                ('default', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_pages_in_menu', models.BooleanField(default=True, help_text='Display pages in menu')),
                ('show_categories_in_menu', models.BooleanField(default=True, help_text='Display categories in menu')),
                ('post_url_template', models.CharField(choices=[('{slug}.html', '<slug>.html'), ('{slug}/index.html', '<slug>/index.html'), ('{date:%Y}/{slug}.html', '<year>/<slug>.html'), ('{date:%Y}/{date:%b}/{slug}.html', '<year>/<month>/<slug>.html'), ('{category}/{slug}.html', '<author>/<slug>.html'), ('{category}/{slug}.html', '<category>/<slug>.html'), ('{category}/{date:%Y}/{slug}.html', '<category>/<year>/<slug>.html')], default='{slug}.html', max_length=255)),
                ('page_url_prefix', models.CharField(blank=True, default='', help_text="Pages URL prefix (pages urls will look like 'prefix/{slug}.html')", max_length=35)),
                ('category_url_prefix', models.CharField(default='category', help_text="Category URL prefix (pages urls will look like 'prefix/{slug}.html')", max_length=35)),
                ('author_url_prefix', models.CharField(default='author', help_text="Author URL prefix (pages urls will look like 'prefix/{slug}.html')", max_length=35)),
                ('tags_url_prefix', models.CharField(default='tags', help_text="Tags URL prefix (it will look like 'prefix/{slug}.html')", max_length=35)),
                ('show_internal_pages_author', models.BooleanField(default=False, help_text='Include authors page')),
                ('show_internal_pages_categories', models.BooleanField(default=True, help_text='Include categories page')),
                ('show_internal_pages_tags', models.BooleanField(default=True, help_text='Include tags page')),
                ('plugins', models.ManyToManyField(blank=True, to='pelican.plugin')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pelican', to='core.site')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('name', models.CharField(blank=True, help_text='Must be set explicitely for cloning a repo under different name', max_length=32, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('blog', 'Blog'), ('conf', 'Conference'), ('corp', 'Company')], default='blog', max_length=4)),
                ('image', models.ImageField(blank=True, help_text='Screenshot images showcasing the theme', null=True, upload_to=velican2.engines.pelican.models.theme_upload_to)),
                ('image1', models.ImageField(blank=True, help_text='Screenshot images showcasing the theme', null=True, upload_to=velican2.engines.pelican.models.theme_upload_to)),
                ('image2', models.ImageField(blank=True, help_text='Screenshot images showcasing the theme', null=True, upload_to=velican2.engines.pelican.models.theme_upload_to)),
                ('logo_size', models.CharField(blank=True, help_text='Ideal logo size in pixels; format: WxH (e.g. 350x200)', max_length=7, null=True)),
                ('supports_custom_css', models.BooleanField(default=False)),
                ('heading_size', models.CharField(blank=True, help_text='Ideal heading size in pixels; format: WxH (e.g. 1280x600)', max_length=9, null=True)),
                ('theme_settings', models.TextField(blank=True, help_text="Define extra variables for the theme (using KEY = 'value' or KEY = conf.EXISTING_KEY)", null=True)),
                ('user_settings', models.TextField(blank=True, help_text="Define extra variables for the theme (using toml syntax: KEY = 'value'", null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.TextField(blank=True, help_text="Define extra variables for the theme (using KEY = 'value' or KEY = conf.EXISTING_KEY)", null=True)),
                ('custom_css', models.TextField(blank=True, help_text='Inject custom CSS', null=True)),
                ('pelican', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelican.settings')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelican.theme')),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pelican.theme'),
        ),
    ]
