# Generated by Django 4.2 on 2023-04-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='github',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='post_url_template',
            field=models.CharField(choices=[('{date:%Y}/{date:%b}/{date:%d}/{slug}.html', '<slug>.html'), ('{slug}/index.html', '<slug>/index.html'), ('{date:%Y}/{slug}.html', '<year>/<slug>.html'), ('{date:%Y}/{date:%b}/{slug}.html', '<year>/<month>/<slug>.html'), ('{category}/{slug}.html', '<author>/<slug>.html'), ('{category}/{slug}.html', '<category>/<slug>.html'), ('{category}/{date:%Y}/{slug}.html', '<category>/<year>/<slug>.html')], default='{date:%Y}/{date:%b}/{date:%d}/{slug}.html', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
