# Generated by Django 4.2 on 2023-05-23 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='themesource',
            name='mapping',
            field=models.TextField(blank=True, help_text="Define extra variables for the theme (using KEY = 'value' or KEY = conf.EXISTING_KEY)", null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='post_url_template',
            field=models.CharField(choices=[('/{slug}.html', '<slug>.html'), ('/{slug}/index.html', '<slug>/index.html'), ('/{date:%Y}/{slug}.html', '<year>/<slug>.html'), ('/{date:%Y}/{date:%b}/{slug}.html', '<year>/<month>/<slug>.html'), ('/{category}/{slug}.html', '<author>/<slug>.html'), ('/{category}/{slug}.html', '<category>/<slug>.html'), ('/{category}/{date:%Y}/{slug}.html', '<category>/<year>/<slug>.html')], default='/{slug}.html', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='mapping',
            field=models.TextField(blank=True, help_text="Define extra variables for the theme (using KEY = 'value' or KEY = conf.EXISTING_KEY)", null=True),
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.TextField(blank=True, help_text="Define extra variables for the theme (using KEY = 'value' or KEY = conf.EXISTING_KEY)", null=True)),
                ('pelican', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelican.settings')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelican.theme')),
            ],
        ),
    ]
