# Generated by Django 4.2 on 2023-05-24 09:17

from django.db import migrations, models
import velican2.engines.pelican.models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0002_settings_instagram_themesource_mapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=velican2.engines.pelican.models.theme_upload_to),
        ),
        migrations.AddField(
            model_name='theme',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=velican2.engines.pelican.models.theme_upload_to),
        ),
        migrations.AddField(
            model_name='theme',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=velican2.engines.pelican.models.theme_upload_to),
        ),
    ]
