# Generated by Django 4.2 on 2023-05-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0003_theme_description_theme_image_theme_image1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={},
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='mapping',
            new_name='theme_settings',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='installed',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='source',
        ),
        migrations.AddField(
            model_name='settings',
            name='show_internal_pages_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='show_internal_pages_categories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='show_internal_pages_tags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='tags_url_prefix',
            field=models.CharField(default='tags', help_text="Tags URL prefix (it will look like 'prefix/{slug}.html')", max_length=35),
        ),
        migrations.AddField(
            model_name='theme',
            name='url',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='user_settings',
            field=models.TextField(blank=True, help_text="Define extra variables for the theme (using KEY = 'value' or KEY = conf.EXISTING_KEY)", null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(blank=True, help_text='Must be set explicitely for cloning a repo under different name', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ThemeSource',
        ),
    ]
