# Generated by Django 4.2 on 2023-06-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0005_plugin_alter_settings_post_url_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='Null for built-in plugins', max_length=265, null=True)),
            ],
            options={
                'verbose_name': 'Plugin',
                'verbose_name_plural': 'Plugins',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='plugins',
            field=models.ManyToManyField(to='pelican.plugin'),
        ),
    ]
