# Generated by Django 4.2 on 2023-06-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0006_plugin_settings_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='default',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
