# Generated by Django 4.2 on 2023-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0008_plugin_name_alter_plugin_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={'verbose_name': 'Theme Settings', 'verbose_name_plural': 'Theme Settings'},
        ),
        migrations.AddField(
            model_name='plugin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='settings',
            name='plugins',
            field=models.ManyToManyField(blank=True, to='pelican.plugin'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='user_settings',
            field=models.TextField(blank=True, help_text="Define extra variables for the theme (using toml syntax: KEY = 'value'", null=True),
        ),
    ]
