# Generated by Django 4.2 on 2023-06-06 14:06

from django.db import migrations, models
import velican2.engines.pelican.models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0009_alter_themesettings_options_plugin_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='heading_size',
            field=models.CharField(blank=True, help_text='Ideal heading size in pixels; format: WxH (e.g. 1280x600)', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='logo_size',
            field=models.CharField(blank=True, help_text='Ideal logo size in pixels; format: WxH (e.g. 350x200)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, help_text='Screenshot images showcasing the theme', null=True, upload_to=velican2.engines.pelican.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image1',
            field=models.ImageField(blank=True, help_text='Screenshot images showcasing the theme', null=True, upload_to=velican2.engines.pelican.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image2',
            field=models.ImageField(blank=True, help_text='Screenshot images showcasing the theme', null=True, upload_to=velican2.engines.pelican.models.theme_upload_to),
        ),
    ]
