# Generated by Django 4.2 on 2023-06-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelican', '0010_theme_heading_size_theme_logo_size_alter_theme_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='supports_custom_css',
            field=models.BooleanField(default=False, help_text='Does the theme support custom CSS?'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Inject custom CSS', null=True),
        ),
    ]
