# Generated by Django 4.2 on 2023-04-14 10:45

import django.core.validators
from django.db import migrations, models
import velican2.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='deployment',
            field=models.CharField(choices=[('caddy', 'local Caddy server')], default='caddy', max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='punchline',
            field=models.TextField(blank=True, help_text='Punchline for social media. Defaults to description.'),
        ),
        migrations.AlterField(
            model_name='site',
            name='allow_crawlers',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this page'),
        ),
        migrations.AlterField(
            model_name='site',
            name='allow_training',
            field=models.BooleanField(default=True, help_text='Allow AI engines to index this page'),
        ),
        migrations.AlterField(
            model_name='site',
            name='domain',
            field=models.CharField(db_index=True, help_text='Example: example.com', max_length=32, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z0-9_\\-]+\\.?)+$')]),
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=velican2.core.models.site_logo_upload),
        ),
        migrations.AlterField(
            model_name='site',
            name='path',
            field=models.CharField(blank=True, default='', help_text='Fill only if your site is under a path (e.g. "/blog")', max_length=32, validators=[django.core.validators.RegexValidator(regex='^([a-zA-Z0-9_\\-]+/?)*$')]),
        ),
    ]
