# Generated by Django 4.2 on 2023-04-27 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publish_post_alter_post_author_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='preview',
        ),
        migrations.AddField(
            model_name='publish',
            name='force',
            field=models.BooleanField(default=False, help_text='Upload all files no matter their modification time'),
        ),
        migrations.AddField(
            model_name='publish',
            name='purge',
            field=models.BooleanField(default=False, help_text='Clear all files in the bucket prior uploading'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='post',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
    ]
