# Generated by Django 4.2 on 2023-09-28 17:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_site_publish_to_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 17, 39, 32, 310451, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
