# Generated by Django 4.2 on 2023-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_admin_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='matomo',
            field=models.BooleanField(default=False, help_text='Should it use builtin tracking service'),
        ),
        migrations.AddField(
            model_name='site',
            name='matomo_external',
            field=models.CharField(help_text='URL of an external tracking service', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='matomo_external_id',
            field=models.CharField(help_text='SITE_ID for the external tracking service', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='webmentions',
            field=models.BooleanField(default=False, help_text='Should it use builtin webmentions service'),
        ),
        migrations.AddField(
            model_name='site',
            name='webmentions_external',
            field=models.CharField(help_text='URL of an external webmentions service', max_length=256, null=True),
        ),
    ]
