# Generated by Django 4.2 on 2023-06-05 15:59

from django.db import migrations, models
import velican2.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_site_matomo_site_matomo_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='heading',
            field=models.ImageField(blank=True, null=True, upload_to=velican2.core.models.content_heading_upload),
        ),
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.ImageField(blank=True, null=True, upload_to=velican2.core.models.content_heading_upload),
        ),
        migrations.AddField(
            model_name='site',
            name='heading',
            field=models.ImageField(blank=True, null=True, upload_to=velican2.core.models.site_heading_upload),
        ),
    ]
