# Generated by Django 4.2 on 2023-06-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_page_heading_post_heading_site_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='google_analytics_code',
            field=models.CharField(blank=True, help_text='Your google analytics code UA-XYZ', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='matomo_external',
            field=models.CharField(blank=True, help_text='URL of an external tracking service', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='matomo_external_id',
            field=models.CharField(blank=True, help_text='SITE_ID for the external tracking service', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='webmentions_external',
            field=models.CharField(blank=True, help_text='URL of an external webmentions service', max_length=256, null=True),
        ),
    ]
