# Generated by Django 4.2 on 2023-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_site_options_post_broadcast_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='fediverse_url',
            field=models.CharField(blank=True, help_text='Your profile URL', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='publish_to_facebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='publish_to_fediverse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='publish_to_instagram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='publish_to_linkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='publish_to_twitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='matomo',
            field=models.BooleanField(default=False, help_text='Should your site use usage-tracking service'),
        ),
        migrations.AlterField(
            model_name='site',
            name='matomo_external',
            field=models.CharField(blank=True, help_text='URL of an usage-tracking service', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='webmentions',
            field=models.BooleanField(default=False, help_text='Should your site use webmentions'),
        ),
        migrations.AlterField(
            model_name='site',
            name='webmentions_external',
            field=models.CharField(blank=True, help_text='URL of an external webmentions service (optional). Leave empty for the builtin service.', max_length=256, null=True),
        ),
    ]
