# Generated by Django 4.2 on 2023-06-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_site_fediverse_url_site_publish_to_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='updated_count',
            field=models.IntegerField(blank=True, default=0, help_text='How many times was the content updated'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_words',
            field=models.IntegerField(blank=True, default=0, help_text='How many words were changed during its lifespan'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_count',
            field=models.IntegerField(blank=True, default=0, help_text='How many times was the content updated'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_words',
            field=models.IntegerField(blank=True, default=0, help_text='How many words were changed during its lifespan'),
        ),
    ]
