# Generated by Django 4.2 on 2023-06-26 08:17

from django.db import migrations, models
import django.db.models.deletion
import velican2.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_page_updated_count_page_updated_words_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='Slug of matching content - must not change during lifetime', max_length=64)),
                ('name', models.CharField(max_length=32, null=True)),
                ('image', models.ImageField(upload_to=velican2.core.models.content_image_upload)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
    ]
