# Generated by Django 4.2 on 2023-09-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_site_publish_to_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(help_text='Git repository for exporting sources for articles', max_length=256)),
                ('username', models.CharField(max_length=52)),
                ('password', models.CharField(help_text='Password or token with write permissions for the repository', max_length=256)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
    ]
