# Generated by Django 4.2 on 2023-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='error',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
